version: '3'

services:
  webserver:
    image: nginx:alpine
    restart: unless-stopped
    tty: true
    environment:
      - NGINX_HOST=local.tech.test
    depends_on:
      - api
    volumes:
      - ./webserver/vhost.conf:/etc/nginx/conf.d/default.conf:ro
      - ./webserver/server.crt:/etc/ssl/certs/server.crt:cached
      - ./webserver/server.key:/etc/ssl/private/server.key:cached
      - ./api:/var/www
    working_dir: /var/www
    ports:
      - "8888:80"
      - "443:443"
    networks:
      - frontend

  api:
    restart: on-failure
    build:
      context: .
      dockerfile: api.dockerfile
    volumes:
      - ./api:/var/www
    depends_on:
      - mysql-db
    networks:
      - backend
      - frontend

  mysql-db:
    image: mysql/mysql-server:5.7
    command: mysqld --performance_schema=on --show_compatibility_56=on
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=r00tPassword
      - MYSQL_DATABASE=interview_tests
      - MYSQL_USER=dev_user
      - MYSQL_PASSWORD=dev_pass
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
      - data-local-storage:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - backend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

volumes:
  data-local-storage: {}
