version: '2.3'

services:
  api:
    restart: on-failure
    build:
      context: .
      dockerfile: api.dockerfile
    volumes:
      - ./api:/var/www
    depends_on:
      - mysql-db
    networks:
      - backend
      - frontend

  mysql-db:
    image: mysql/mysql-server:5.7
    command: mysqld --performance_schema=on --show_compatibility_56=on
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=r00tPassword
      - MYSQL_DATABASE=interview_tests
      - MYSQL_USER=dev_user
      - MYSQL_PASSWORD=dev_pass
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
      - data-local-storage:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - backend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

volumes:
  data-local-storage: {}
